language: rust

rust:
- 1.13.0
- stable
- nightly

env:
- 
- CARGO_BUILD_TARGET=arm-linux-androideabi

os:
  - linux

script:
  - if [[ $CARGO_BUILD_TARGET ]]; then
      rustup target add $CARGO_BUILD_TARGET;
    fi
  - cargo build --verbose
  - if [[ $TRAVIS_RUST_VERSION = nightly* && -e "$CARGO_BUILD_TARGET" ]]; then
      env RUST_BACKTRACE=1 cargo test -v;
    fi
